// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Home_Scr.h"
#include "screens/ui_Music_scr.h"
#include "screens/ui_Number_scr.h"
#include "screens/ui_Vlaga_scr.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HideBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowBtn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
