// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void prev_song(lv_event_t * e);
void pause_song(lv_event_t * e);
void next_song(lv_event_t * e);
void NextPjesma(lv_event_t * e);
void slikaj_sliku(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
