// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"

void dark_mode_on(lv_event_t * e)
{
	// Your code here
}

void dark_mode_off(lv_event_t * e)
{
	// Your code here
}

void prev_song(lv_event_t * e)
{
	// Your code here
}

void pause_song(lv_event_t * e)
{
	// Your code here
}

void next_song(lv_event_t * e)
{
	// Your code here
}

void slikaj_sliku(lv_event_t * e)
{
	// Your code here
}

void NextPjesma(lv_event_t * e)
{
	// Your code here
}
