// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_COLOR_SCR_H
#define UI_COLOR_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Color_Scr
extern void ui_Color_Scr_screen_init(void);
extern void ui_Color_Scr_screen_destroy(void);
extern lv_obj_t * ui_Color_Scr;
extern void ui_event_Dark_Mode_Switch_Color(lv_event_t * e);
extern lv_obj_t * ui_Dark_Mode_Switch_Color;
extern lv_obj_t * ui_Dark_Mode_Label_Color;
extern void ui_event_Home_Btn_Color(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Color;
extern lv_obj_t * ui_Home_Img_C;
extern lv_obj_t * ui_BL_logo_Color;
extern lv_obj_t * ui_Colorwheel;
extern lv_obj_t * ui_LED_color_panel;
extern lv_obj_t * ui_LED_color_label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

