// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef UI_HOME_SCR_H
#define UI_HOME_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home_Scr
extern void ui_Home_Scr_screen_init(void);
extern void ui_Home_Scr_screen_destroy(void);
extern lv_obj_t * ui_Home_Scr;
extern void ui_event_BTN_Num(lv_event_t * e);
extern lv_obj_t * ui_BTN_Num;
extern void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern void ui_event_Settings_Btn_Home(lv_event_t * e);
extern lv_obj_t * ui_Settings_Btn_Home;
extern void ui_event_Settings_Icon_Home(lv_event_t * e);
extern lv_obj_t * ui_Settings_Icon_Home;
extern lv_obj_t * ui_welcomelabel;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

