// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Home_Scr = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_camImage = NULL;
// event funtions

// build funtions

void ui_Home_Scr_screen_init(void)
{
    ui_Home_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Scr, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Home_Scr);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 1);
    lv_obj_set_y(ui_temp, -97);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_camImage = lv_img_create(ui_Home_Scr);
    lv_obj_set_width(ui_camImage, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_camImage, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_camImage, -4);
    lv_obj_set_y(ui_camImage, -5);
    lv_obj_set_align(ui_camImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_camImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_camImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Home_Scr_screen_destroy(void)
{
    if(ui_Home_Scr) lv_obj_del(ui_Home_Scr);

    // NULL screen variables
    ui_Home_Scr = NULL;
    ui_temp = NULL;
    ui_camImage = NULL;

}
