// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Home_Scr = NULL;
lv_obj_t * ui_BTN_Num = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Settings_Btn_Home = NULL;
lv_obj_t * ui_Settings_Icon_Home = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions
void ui_event_BTN_Num(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Number_scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Number_scr_screen_init);
    }
}

void ui_event_Settings_Btn_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Number_scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_Number_scr_screen_init);
    }
}

void ui_event_Settings_Icon_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Music_scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Music_scr_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Vlaga_scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Vlaga_scr_screen_init);
    }
}

void ui_event_Image2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Vlaga_scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Vlaga_scr_screen_init);
    }
}

// build funtions

void ui_Home_Scr_screen_init(void)
{
    ui_Home_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Home_Scr, &ui_img_bg16_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Home_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Home_Scr, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTN_Num = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_BTN_Num, 75);
    lv_obj_set_height(ui_BTN_Num, 68);
    lv_obj_set_x(ui_BTN_Num, -103);
    lv_obj_set_y(ui_BTN_Num, 50);
    lv_obj_set_align(ui_BTN_Num, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTN_Num, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BTN_Num, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BTN_Num, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTN_Num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BTN_Num, lv_color_hex(0xB2ECD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BTN_Num, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTN_Num, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_BTN_Num, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_BTN_Num);
    lv_img_set_src(ui_Image8, &ui_img_5224653);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image8, -1);
    lv_obj_set_y(ui_Image8, 0);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image8, 500);

    ui_Settings_Btn_Home = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_Settings_Btn_Home, 75);
    lv_obj_set_height(ui_Settings_Btn_Home, 68);
    lv_obj_set_y(ui_Settings_Btn_Home, 50);
    lv_obj_set_x(ui_Settings_Btn_Home, lv_pct(0));
    lv_obj_set_align(ui_Settings_Btn_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings_Btn_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Settings_Btn_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_Btn_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Btn_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings_Btn_Home, lv_color_hex(0xB2EED4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settings_Btn_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Settings_Btn_Home, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Settings_Btn_Home, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_Icon_Home = lv_img_create(ui_Settings_Btn_Home);
    lv_img_set_src(ui_Settings_Icon_Home, &ui_img_2121686456);
    lv_obj_set_width(ui_Settings_Icon_Home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Icon_Home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings_Icon_Home, -1);
    lv_obj_set_y(ui_Settings_Icon_Home, 1);
    lv_obj_set_align(ui_Settings_Icon_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings_Icon_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Settings_Icon_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Settings_Icon_Home, 150);

    ui_temp = lv_label_create(ui_Home_Scr);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 1);
    lv_obj_set_y(ui_temp, -85);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "Welcome Back");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_Button1, 75);
    lv_obj_set_height(ui_Button1, 68);
    lv_obj_set_x(ui_Button1, 104);
    lv_obj_set_y(ui_Button1, 50);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x6CC7A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0xB2EDD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Button1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Button1);
    lv_img_set_src(ui_Image2, &ui_img_dots_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image2, 1);
    lv_obj_set_y(ui_Image2, 3);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BTN_Num, ui_event_BTN_Num, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings_Icon_Home, ui_event_Settings_Icon_Home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings_Btn_Home, ui_event_Settings_Btn_Home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image2, ui_event_Image2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Home_Scr_screen_destroy(void)
{
    if(ui_Home_Scr) lv_obj_del(ui_Home_Scr);

    // NULL screen variables
    ui_Home_Scr = NULL;
    ui_BTN_Num = NULL;
    ui_Image8 = NULL;
    ui_Settings_Btn_Home = NULL;
    ui_Settings_Icon_Home = NULL;
    ui_temp = NULL;
    ui_Button1 = NULL;
    ui_Image2 = NULL;

}
