// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Home_Scr = NULL;
lv_obj_t * ui_Color_Btn_Home = NULL;
lv_obj_t * ui_Colorwheel_Home = NULL;
lv_obj_t * ui_BL_logo_Home = NULL;
lv_obj_t * ui_Dark_Mode_Label = NULL;
lv_obj_t * ui_Dark_Mode_Switch = NULL;
lv_obj_t * ui_Settings_Btn_Home = NULL;
lv_obj_t * ui_Settings_Icon_Home = NULL;
lv_obj_t * ui_temp = NULL;
// event funtions
void ui_event_Color_Btn_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SpinAndLargen_Animation(ui_Colorwheel_Home, 0);
        LargeBtn_Animation(ui_Color_Btn_Home, 0);
        MoveColorToCenter_Animation(ui_Color_Btn_Home, 0);
        HideBtn_Animation(ui_Settings_Btn_Home, 0);
        ShowBtn_Animation(ui_Settings_Btn_Home, 1200);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Color_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_Color_Scr_screen_init);
    }
}

void ui_event_Dark_Mode_Switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        dark_mode_on(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        dark_mode_off(e);
    }
}

void ui_event_Settings_Btn_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        SpinAndLargen_Animation(ui_Settings_Icon_Home, 0);
        LargeBtn_Animation(ui_Settings_Btn_Home, 0);
        MoveSettingsToCenter_Animation(ui_Settings_Btn_Home, 0);
        HideBtn_Animation(ui_Color_Btn_Home, 0);
        ShowBtn_Animation(ui_Color_Btn_Home, 1200);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 1000, &ui_Settings_Scr_screen_init);
    }
}

// build funtions

void ui_Home_Scr_screen_init(void)
{
    ui_Home_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Scr, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Color_Btn_Home = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_Color_Btn_Home, 75);
    lv_obj_set_height(ui_Color_Btn_Home, 68);
    lv_obj_set_x(ui_Color_Btn_Home, -64);
    lv_obj_set_y(ui_Color_Btn_Home, 0);
    lv_obj_set_align(ui_Color_Btn_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Color_Btn_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Color_Btn_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color_Btn_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color_Btn_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Colorwheel_Home = lv_img_create(ui_Color_Btn_Home);
    lv_img_set_src(ui_Colorwheel_Home, &ui_img_colorwheel_icon_png);
    lv_obj_set_width(ui_Colorwheel_Home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Colorwheel_Home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Colorwheel_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Colorwheel_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Colorwheel_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Colorwheel_Home, 120);

    ui_BL_logo_Home = lv_img_create(ui_Home_Scr);
    lv_img_set_src(ui_BL_logo_Home, &ui_img_bl_logo_symbol_png);
    lv_obj_set_width(ui_BL_logo_Home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BL_logo_Home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BL_logo_Home, 139);
    lv_obj_set_y(ui_BL_logo_Home, -101);
    lv_obj_set_align(ui_BL_logo_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BL_logo_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BL_logo_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BL_logo_Home, 50);

    ui_Dark_Mode_Label = lv_label_create(ui_Home_Scr);
    lv_obj_set_width(ui_Dark_Mode_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dark_Mode_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dark_Mode_Label, 76);
    lv_obj_set_y(ui_Dark_Mode_Label, 107);
    lv_obj_set_align(ui_Dark_Mode_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dark_Mode_Label, "Dark mode");
    lv_obj_set_style_text_color(ui_Dark_Mode_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Dark_Mode_Switch = lv_switch_create(ui_Home_Scr);
    lv_obj_set_width(ui_Dark_Mode_Switch, 32);
    lv_obj_set_height(ui_Dark_Mode_Switch, 15);
    lv_obj_set_x(ui_Dark_Mode_Switch, 139);
    lv_obj_set_y(ui_Dark_Mode_Switch, 107);
    lv_obj_set_align(ui_Dark_Mode_Switch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Dark_Mode_Switch, LV_STATE_CHECKED);       /// States

    lv_obj_set_style_bg_color(ui_Dark_Mode_Switch, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Dark_Mode_Switch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Settings_Btn_Home = lv_btn_create(ui_Home_Scr);
    lv_obj_set_width(ui_Settings_Btn_Home, 75);
    lv_obj_set_height(ui_Settings_Btn_Home, 68);
    lv_obj_set_y(ui_Settings_Btn_Home, -1);
    lv_obj_set_x(ui_Settings_Btn_Home, lv_pct(20));
    lv_obj_set_align(ui_Settings_Btn_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings_Btn_Home, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Settings_Btn_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_Btn_Home, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Btn_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_Icon_Home = lv_img_create(ui_Settings_Btn_Home);
    lv_img_set_src(ui_Settings_Icon_Home, &ui_img_settings_icon_png);
    lv_obj_set_width(ui_Settings_Icon_Home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Icon_Home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Settings_Icon_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings_Icon_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Settings_Icon_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Settings_Icon_Home, 120);
    lv_obj_set_style_bg_color(ui_Settings_Icon_Home, lv_color_hex(0xF50707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Icon_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Home_Scr);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 1);
    lv_obj_set_y(ui_temp, -97);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Color_Btn_Home, ui_event_Color_Btn_Home, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dark_Mode_Switch, ui_event_Dark_Mode_Switch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings_Btn_Home, ui_event_Settings_Btn_Home, LV_EVENT_ALL, NULL);

}

void ui_Home_Scr_screen_destroy(void)
{
    if(ui_Home_Scr) lv_obj_del(ui_Home_Scr);

    // NULL screen variables
    ui_Home_Scr = NULL;
    ui_Color_Btn_Home = NULL;
    ui_Colorwheel_Home = NULL;
    ui_BL_logo_Home = NULL;
    ui_Dark_Mode_Label = NULL;
    ui_Dark_Mode_Switch = NULL;
    ui_Settings_Btn_Home = NULL;
    ui_Settings_Icon_Home = NULL;
    ui_temp = NULL;

}
