// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_HOME_SCR_H
#define UI_HOME_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home_Scr
extern void ui_Home_Scr_screen_init(void);
extern void ui_Home_Scr_screen_destroy(void);
extern lv_obj_t * ui_Home_Scr;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_camImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

