// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Music_scr = NULL;
lv_obj_t * ui_LED_color_panel = NULL;
lv_obj_t * ui_LED_color_label = NULL;
lv_obj_t * ui_svemir = NULL;
lv_obj_t * ui_playButton = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Image9 = NULL;
// event funtions
void ui_event_playButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        pause_song(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_Scr_screen_init);
    }
}

// build funtions

void ui_Music_scr_screen_init(void)
{
    ui_Music_scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Music_scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Music_scr, lv_color_hex(0x220404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Music_scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LED_color_panel = lv_obj_create(ui_Music_scr);
    lv_obj_set_width(ui_LED_color_panel, 139);
    lv_obj_set_height(ui_LED_color_panel, 31);
    lv_obj_set_x(ui_LED_color_panel, -3);
    lv_obj_set_y(ui_LED_color_panel, -96);
    lv_obj_set_align(ui_LED_color_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LED_color_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LED_color_panel, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LED_color_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LED_color_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LED_color_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LED_color_label = lv_label_create(ui_LED_color_panel);
    lv_obj_set_width(ui_LED_color_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LED_color_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LED_color_label, 2);
    lv_obj_set_y(ui_LED_color_label, 1);
    lv_obj_set_align(ui_LED_color_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LED_color_label, "PJESMICE");
    lv_obj_set_style_text_font(ui_LED_color_label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_svemir = lv_label_create(ui_Music_scr);
    lv_obj_set_width(ui_svemir, lv_pct(50));
    lv_obj_set_height(ui_svemir, lv_pct(10));
    lv_obj_set_x(ui_svemir, -2);
    lv_obj_set_y(ui_svemir, -43);
    lv_obj_set_align(ui_svemir, LV_ALIGN_CENTER);
    lv_label_set_text(ui_svemir, "DEVITO - SVEMIR");
    lv_obj_set_style_text_align(ui_svemir, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_svemir, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_svemir, lv_color_hex(0x0FC46D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_svemir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_playButton = lv_btn_create(ui_Music_scr);
    lv_obj_set_width(ui_playButton, 75);
    lv_obj_set_height(ui_playButton, 68);
    lv_obj_set_x(ui_playButton, 2);
    lv_obj_set_y(ui_playButton, 31);
    lv_obj_set_align(ui_playButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_playButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_playButton);
    lv_img_set_src(ui_Image4, &ui_img_pause_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_Music_scr);
    lv_obj_set_width(ui_Button7, 75);
    lv_obj_set_height(ui_Button7, 75);
    lv_obj_set_x(ui_Button7, 119);
    lv_obj_set_y(ui_Button7, -83);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_img_create(ui_Button7);
    lv_img_set_src(ui_Image9, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 86
    lv_obj_set_x(ui_Image9, -1);
    lv_obj_set_y(ui_Image9, -3);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image9, 150);

    lv_obj_add_event_cb(ui_playButton, ui_event_playButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);

}

void ui_Music_scr_screen_destroy(void)
{
    if(ui_Music_scr) lv_obj_del(ui_Music_scr);

    // NULL screen variables
    ui_Music_scr = NULL;
    ui_LED_color_panel = NULL;
    ui_LED_color_label = NULL;
    ui_svemir = NULL;
    ui_playButton = NULL;
    ui_Image4 = NULL;
    ui_Button7 = NULL;
    ui_Image9 = NULL;

}
