// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef UI_MUSIC_SCR_H
#define UI_MUSIC_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Music_scr
extern void ui_Music_scr_screen_init(void);
extern void ui_Music_scr_screen_destroy(void);
extern lv_obj_t * ui_Music_scr;
extern void ui_event_Home_Btn_Color(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Color;
extern void ui_event_Home_Img_C(lv_event_t * e);
extern lv_obj_t * ui_Home_Img_C;
extern lv_obj_t * ui_LED_color_panel;
extern lv_obj_t * ui_LED_color_label;
extern lv_obj_t * ui_songlabel;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image5;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image4;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

