// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef UI_NUMBER_SCR_H
#define UI_NUMBER_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Number_scr
extern void ui_Number_scr_screen_init(void);
extern void ui_Number_scr_screen_destroy(void);
extern lv_obj_t * ui_Number_scr;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_SlikaBrojeva;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

