// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef UI_SETTINGS_SCR_H
#define UI_SETTINGS_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings_Scr
extern void ui_Settings_Scr_screen_init(void);
extern void ui_Settings_Scr_screen_destroy(void);
extern lv_obj_t * ui_Settings_Scr;
extern void ui_event_Dark_Mode_Switch_Sett(lv_event_t * e);
extern lv_obj_t * ui_Dark_Mode_Switch_Sett;
extern lv_obj_t * ui_Dark_Mode_Label_Sett;
extern void ui_event_Home_Btn_Sett(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Sett;
extern lv_obj_t * ui_Home_Img_S;
extern lv_obj_t * ui_BL_logo_Sett;
extern lv_obj_t * ui_Settings_scroll_panel;
extern lv_obj_t * ui_Checkbox_Sett;
extern lv_obj_t * ui_Dropdown_Sett;
extern lv_obj_t * ui_Roller_Sett;
extern lv_obj_t * ui_Slider1_Sett;
extern void ui_event_Text_area(lv_event_t * e);
extern lv_obj_t * ui_Text_area;
extern lv_obj_t * ui_Arc_Sett;
extern lv_obj_t * ui_Slider2_Sett;
extern void ui_event_Keyboard_Sett(lv_event_t * e);
extern lv_obj_t * ui_Keyboard_Sett;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

