// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Vlaga_scr = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Vlagavalue = NULL;
lv_obj_t * ui_temp = NULL;
// event funtions

// build funtions

void ui_Vlaga_scr_screen_init(void)
{
    ui_Vlaga_scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Vlaga_scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Vlaga_scr);
    lv_obj_set_width(ui_Label3, lv_pct(38));
    lv_obj_set_height(ui_Label3, lv_pct(18));
    lv_obj_set_x(ui_Label3, -97);
    lv_obj_set_y(ui_Label3, -58);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Vlaga:");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Vlaga_scr);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -45);
    lv_obj_set_y(ui_Label4, 19);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Temperatura: ");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Vlagavalue = lv_label_create(ui_Vlaga_scr);
    lv_obj_set_width(ui_Vlagavalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Vlagavalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Vlagavalue, 93);
    lv_obj_set_y(ui_Vlagavalue, -57);
    lv_obj_set_align(ui_Vlagavalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Vlagavalue, "0");
    lv_obj_set_style_text_color(ui_Vlagavalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Vlagavalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Vlagavalue, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Vlaga_scr);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 93);
    lv_obj_set_y(ui_temp, 25);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "0");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Vlaga_scr_screen_destroy(void)
{
    if(ui_Vlaga_scr) lv_obj_del(ui_Vlaga_scr);

    // NULL screen variables
    ui_Vlaga_scr = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Vlagavalue = NULL;
    ui_temp = NULL;

}
