// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef UI_VLAGA_SCR_H
#define UI_VLAGA_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Vlaga_scr
extern void ui_Vlaga_scr_screen_init(void);
extern void ui_Vlaga_scr_screen_destroy(void);
extern lv_obj_t * ui_Vlaga_scr;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Vlagavalue;
extern lv_obj_t * ui_temp;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Image10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

